apiVersion: v1
kind: Service
metadata:
  name: users-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: doc2346613/kub-dep-users:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://eks_db_user:urEYrgrVBFUIbsXL@cluster0.i7uxgy2.mongodb.net/users?appName=Cluster0"
            - name: AUTH_API_ADDRESS
              value: "auth-service.default:3000"
